import {Container} from "react-bootstrap";

const LottoLicense = () => {
    const text = "#Flutter\n"
        + "\n"
        + "        Copyright 2014 The Flutter Authors. All rights reserved.\n"
        + "\n"
        + "        Redistribution and use in source and binary forms, with or without modification,\n"
        + "        are permitted provided that the following conditions are met:\n"
        + "\n"
        + "            * Redistributions of source code must retain the above copyright\n"
        + "              notice, this list of conditions and the following disclaimer.\n"
        + "            * Redistributions in binary form must reproduce the above\n"
        + "              copyright notice, this list of conditions and the following\n"
        + "              disclaimer in the documentation and/or other materials provided\n"
        + "              with the distribution.\n"
        + "            * Neither the name of Google Inc. nor the names of its\n"
        + "              contributors may be used to endorse or promote products derived\n"
        + "              from this software without specific prior written permission.\n"
        + "\n"
        + "        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\n"
        + "        ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
        + "        WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
        + "        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR\n"
        + "        ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
        + "        (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
        + "        LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n"
        + "        ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        + "        (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
        + "        SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        + "\n"
        + "        #GETX\n"
        + "\n"
        + "        MIT License\n"
        + "\n"
        + "        Copyright (c) 2019 Jonny Borges\n"
        + "\n"
        + "        Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        + "        of this software and associated documentation files (the \"Software\"), to deal\n"
        + "        in the Software without restriction, including without limitation the rights\n"
        + "        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        + "        copies of the Software, and to permit persons to whom the Software is\n"
        + "        furnished to do so, subject to the following conditions:\n"
        + "\n"
        + "        The above copyright notice and this permission notice shall be included in all\n"
        + "        copies or substantial portions of the Software.\n"
        + "\n"
        + "        THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        + "        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        + "        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        + "        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        + "        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        + "        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        + "        SOFTWARE.\n"
        + "\n"
        + "        #webview_flutter\n"
        + "\n"
        + "        Copyright 2013 The Flutter Authors. All rights reserved.\n"
        + "\n"
        + "        Redistribution and use in source and binary forms, with or without modification,\n"
        + "        are permitted provided that the following conditions are met:\n"
        + "\n"
        + "            * Redistributions of source code must retain the above copyright\n"
        + "              notice, this list of conditions and the following disclaimer.\n"
        + "            * Redistributions in binary form must reproduce the above\n"
        + "              copyright notice, this list of conditions and the following\n"
        + "              disclaimer in the documentation and/or other materials provided\n"
        + "              with the distribution.\n"
        + "            * Neither the name of Google Inc. nor the names of its\n"
        + "              contributors may be used to endorse or promote products derived\n"
        + "              from this software without specific prior written permission.\n"
        + "\n"
        + "        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\n"
        + "        ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
        + "        WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
        + "        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR\n"
        + "        ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
        + "        (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
        + "        LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n"
        + "        ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        + "        (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
        + "        SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        + "\n"
        + "        #intl\n"
        + "\n"
        + "        Copyright 2013, the Dart project authors.\n"
        + "\n"
        + "        Redistribution and use in source and binary forms, with or without\n"
        + "        modification, are permitted provided that the following conditions are\n"
        + "        met:\n"
        + "\n"
        + "            * Redistributions of source code must retain the above copyright\n"
        + "              notice, this list of conditions and the following disclaimer.\n"
        + "            * Redistributions in binary form must reproduce the above\n"
        + "              copyright notice, this list of conditions and the following\n"
        + "              disclaimer in the documentation and/or other materials provided\n"
        + "              with the distribution.\n"
        + "            * Neither the name of Google LLC nor the names of its\n"
        + "              contributors may be used to endorse or promote products derived\n"
        + "              from this software without specific prior written permission.\n"
        + "\n"
        + "        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
        + "        \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
        + "        LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
        + "        A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
        + "        OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
        + "        SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
        + "        LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
        + "        DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
        + "        THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        + "        (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
        + "        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        + "\n"
        + "        #flutter_shimmer\n"
        + "\n"
        + "        Copyright 2013, the Dart project authors. All rights reserved.\n"
        + "        Redistribution and use in source and binary forms, with or without\n"
        + "        modification, are permitted provided that the following conditions are\n"
        + "        met:\n"
        + "\n"
        + "            * Redistributions of source code must retain the above copyright\n"
        + "              notice, this list of conditions and the following disclaimer.\n"
        + "            * Redistributions in binary form must reproduce the above\n"
        + "              copyright notice, this list of conditions and the following\n"
        + "              disclaimer in the documentation and/or other materials provided\n"
        + "              with the distribution.\n"
        + "            * Neither the name of Google Inc. nor the names of its\n"
        + "              contributors may be used to endorse or promote products derived\n"
        + "              from this software without specific prior written permission.\n"
        + "\n"
        + "        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
        + "        \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
        + "        LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
        + "        A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
        + "        OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
        + "        SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
        + "        LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
        + "        DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
        + "        THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        + "        (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
        + "        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        + "\n"
        + "        #url_launcher\n"
        + "\n"
        + "        Copyright 2013 The Flutter Authors. All rights reserved.\n"
        + "\n"
        + "        Redistribution and use in source and binary forms, with or without modification,\n"
        + "        are permitted provided that the following conditions are met:\n"
        + "\n"
        + "            * Redistributions of source code must retain the above copyright\n"
        + "              notice, this list of conditions and the following disclaimer.\n"
        + "            * Redistributions in binary form must reproduce the above\n"
        + "              copyright notice, this list of conditions and the following\n"
        + "              disclaimer in the documentation and/or other materials provided\n"
        + "              with the distribution.\n"
        + "            * Neither the name of Google Inc. nor the names of its\n"
        + "              contributors may be used to endorse or promote products derived\n"
        + "              from this software without specific prior written permission.\n"
        + "\n"
        + "        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\n"
        + "        ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
        + "        WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
        + "        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR\n"
        + "        ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
        + "        (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
        + "        LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n"
        + "        ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        + "        (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
        + "        SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        + "\n"
        + "        #package_info_plus\n"
        + "\n"
        + "        // Copyright 2017 The Chromium Authors. All rights reserved.\n"
        + "        //\n"
        + "        // Redistribution and use in source and binary forms, with or without\n"
        + "        // modification, are permitted provided that the following conditions are\n"
        + "        // met:\n"
        + "        //\n"
        + "        //    * Redistributions of source code must retain the above copyright\n"
        + "        // notice, this list of conditions and the following disclaimer.\n"
        + "        //    * Redistributions in binary form must reproduce the above\n"
        + "        // copyright notice, this list of conditions and the following disclaimer\n"
        + "        // in the documentation and/or other materials provided with the\n"
        + "        // distribution.\n"
        + "        //    * Neither the name of Google Inc. nor the names of its\n"
        + "        // contributors may be used to endorse or promote products derived from\n"
        + "        // this software without specific prior written permission.\n"
        + "        //\n"
        + "        // THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
        + "        // \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
        + "        // LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
        + "        // A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
        + "        // OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
        + "        // SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
        + "        // LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
        + "        // DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
        + "        // THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        + "        // (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
        + "        // OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        + "\n"
        + "        #numberpicker\n"
        + "\n"
        + "        Copyright 2017 Marcin Szalek\n"
        + "\n"
        + "        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n"
        + "\n"
        + "        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\n"
        + "\n"
        + "        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.\n"
        + "\n"
        + "        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";

  return <>
    <Container className="mt-5" fluid>
        {text.split("\n").map((text, index)=><div key={`text-${index}`}>{text}</div>)}
    </Container>
  </>
}

export default LottoLicense;
